from backend.controllers import game_controller


def register(router):
    router.add("GET", "/api/map", game_controller.map_payload)
    router.add("GET", "/api/catalog", game_controller.catalog)
    router.add("GET", "/api/progression", game_controller.progression)
    router.add("GET", "/api/inventory", game_controller.inventory)
    router.add("POST", "/api/cards/draw", game_controller.draw)
    router.add("POST", "/api/cards/draw-trajets", game_controller.draw_trajets)
    router.add("POST", "/api/cards/complete", game_controller.complete_card)
    router.add("POST", "/api/cards/apply", game_controller.apply_card)
    router.add("POST", "/api/cards/discard", game_controller.discard_card)
    router.add("POST", "/api/move", game_controller.move_to_node)
    router.add("GET", "/api/skins", game_controller.skins)
    router.add("POST", "/api/skins/equip", game_controller.equip)
    router.add("POST", "/api/skins/open-lootbox", game_controller.open_skin_lootbox)
    router.add("POST", "/api/skins/fuse", game_controller.fuse_skin_copies)
    router.add("GET", "/api/history", game_controller.history)
    router.add("GET", "/api/sessions", game_controller.sessions)
    router.add("POST", "/api/sessions/create", game_controller.create_game_session)
    router.add("POST", "/api/sessions/join", game_controller.join_game_session)
    router.add("POST", "/api/sessions/get", game_controller.get_game_session)
    router.add("GET", "/api/sessions/spawns", game_controller.spawns)
    router.add("POST", "/api/sessions/select-spawn", game_controller.select_game_spawn)
    router.add("POST", "/api/sessions/start", game_controller.start_game_session)
    router.add("POST", "/api/sessions/choose-starting-trajets", game_controller.choose_game_starting_trajets)
    router.add("POST", "/api/sessions/leave", game_controller.leave_game_session)
    router.add("POST", "/api/sessions/end-turn", game_controller.end_turn)
    router.add("POST", "/api/sessions/roll-die", game_controller.roll_session_die)
    router.add("POST", "/api/tasks/activate", game_controller.activate_city_task)
    router.add("POST", "/api/tasks/complete", game_controller.complete_city_task)
    router.add("POST", "/api/services/use", game_controller.use_service)
    router.add("POST", "/api/carpoolers/accept", game_controller.accept_session_carpooler)
    router.add("POST", "/api/player-interactions/use", game_controller.interact_with_player)
